---

name: Workflows for cowmessage exo


on:
  push:
    branches:
        - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Take Code-Hex/Neo-cowsay/v2 and go run .
        run: |
          go get github.com/Code-Hex/Neo-cowsay/v2
          go run .
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cowmessage
          path: .

  deploy:
    runs-on: go
    needs: build
    permissions:
      id-token: write

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        run: sudo snap install go --classic

      - name: Download artifact
        id: deployment
        uses: actions/download-artifact@v4
        with:
          name: cowmessage
          path: ./

